/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAgentRouteImport } from './routes/app.agent'
import { Route as AppCityRouteImport } from './routes/app.city'
import { Route as AppImpactRouteImport } from './routes/app.impact'
import { Route as AppMapRouteImport } from './routes/app.map'
import { Route as AppPredictionRouteImport } from './routes/app.prediction'
import { Route as AppSafeRouteRouteImport } from './routes/app.safe-route'
import { Route as AppSimulatorRouteImport } from './routes/app.simulator'
import { Route as AppWorkerRouteImport } from './routes/app.worker'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppCityRoute = AppCityRouteImport.update({
  id: '/city',
  path: '/city',
  getParentRoute: () => AppRoute,
} as any)
const AppImpactRoute = AppImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppPredictionRoute = AppPredictionRouteImport.update({
  id: '/prediction',
  path: '/prediction',
  getParentRoute: () => AppRoute,
} as any)
const AppSafeRouteRoute = AppSafeRouteRouteImport.update({
  id: '/safe-route',
  path: '/safe-route',
  getParentRoute: () => AppRoute,
} as any)
const AppSimulatorRoute = AppSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkerRoute = AppWorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/agent': typeof AppAgentRoute
  '/app/city': typeof AppCityRoute
  '/app/impact': typeof AppImpactRoute
  '/app/map': typeof AppMapRoute
  '/app/prediction': typeof AppPredictionRoute
  '/app/safe-route': typeof AppSafeRouteRoute
  '/app/simulator': typeof AppSimulatorRoute
  '/app/worker': typeof AppWorkerRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/agent': typeof AppAgentRoute
  '/app/city': typeof AppCityRoute
  '/app/impact': typeof AppImpactRoute
  '/app/map': typeof AppMapRoute
  '/app/prediction': typeof AppPredictionRoute
  '/app/safe-route': typeof AppSafeRouteRoute
  '/app/simulator': typeof AppSimulatorRoute
  '/app/worker': typeof AppWorkerRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/agent': typeof AppAgentRoute
  '/app/city': typeof AppCityRoute
  '/app/impact': typeof AppImpactRoute
  '/app/map': typeof AppMapRoute
  '/app/prediction': typeof AppPredictionRoute
  '/app/safe-route': typeof AppSafeRouteRoute
  '/app/simulator': typeof AppSimulatorRoute
  '/app/worker': typeof AppWorkerRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/agent'
    | '/app/city'
    | '/app/impact'
    | '/app/map'
    | '/app/prediction'
    | '/app/safe-route'
    | '/app/simulator'
    | '/app/worker'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/app/agent'
    | '/app/city'
    | '/app/impact'
    | '/app/map'
    | '/app/prediction'
    | '/app/safe-route'
    | '/app/simulator'
    | '/app/worker'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/agent'
    | '/app/city'
    | '/app/impact'
    | '/app/map'
    | '/app/prediction'
    | '/app/safe-route'
    | '/app/simulator'
    | '/app/worker'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agent': {
      id: '/app/agent'
      path: '/agent'
      fullPath: '/app/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/city': {
      id: '/app/city'
      path: '/city'
      fullPath: '/app/city'
      preLoaderRoute: typeof AppCityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/impact': {
      id: '/app/impact'
      path: '/impact'
      fullPath: '/app/impact'
      preLoaderRoute: typeof AppImpactRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/prediction': {
      id: '/app/prediction'
      path: '/prediction'
      fullPath: '/app/prediction'
      preLoaderRoute: typeof AppPredictionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/safe-route': {
      id: '/app/safe-route'
      path: '/safe-route'
      fullPath: '/app/safe-route'
      preLoaderRoute: typeof AppSafeRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/simulator': {
      id: '/app/simulator'
      path: '/simulator'
      fullPath: '/app/simulator'
      preLoaderRoute: typeof AppSimulatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/worker': {
      id: '/app/worker'
      path: '/worker'
      fullPath: '/app/worker'
      preLoaderRoute: typeof AppWorkerRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgentRoute: typeof AppAgentRoute
  AppCityRoute: typeof AppCityRoute
  AppImpactRoute: typeof AppImpactRoute
  AppMapRoute: typeof AppMapRoute
  AppPredictionRoute: typeof AppPredictionRoute
  AppSafeRouteRoute: typeof AppSafeRouteRoute
  AppSimulatorRoute: typeof AppSimulatorRoute
  AppWorkerRoute: typeof AppWorkerRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentRoute: AppAgentRoute,
  AppCityRoute: AppCityRoute,
  AppImpactRoute: AppImpactRoute,
  AppMapRoute: AppMapRoute,
  AppPredictionRoute: AppPredictionRoute,
  AppSafeRouteRoute: AppSafeRouteRoute,
  AppSimulatorRoute: AppSimulatorRoute,
  AppWorkerRoute: AppWorkerRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
